language: node_js
node_js:
  - "0.12"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - gem install sass
  - npm install -g bower grunt-cli
  - bower install

script: "grunt test --verbose"

git:
  depth: 10